// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9hbfz5canvt87ce3mpMigT0HSDxBluVs',
    appId: '1:788354651482:web:bc6a3b28f8d1851c550f63',
    messagingSenderId: '788354651482',
    projectId: 'owndeck-c-p',
    authDomain: 'owndeck-c-p.firebaseapp.com',
    storageBucket: 'owndeck-c-p.firebasestorage.app',
    measurementId: 'G-RMYC5B4H2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcOiK8N1IaWXhFAUCaFwhxBgw_jSx37k0',
    appId: '1:788354651482:android:b3dd4071c5fb4244550f63',
    messagingSenderId: '788354651482',
    projectId: 'owndeck-c-p',
    storageBucket: 'owndeck-c-p.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN2OTbo73t82695VfXtuXF6eIlAt-3whE',
    appId: '1:788354651482:ios:78c14ae11eb4d373550f63',
    messagingSenderId: '788354651482',
    projectId: 'owndeck-c-p',
    storageBucket: 'owndeck-c-p.firebasestorage.app',
    iosBundleId: 'com.example.owndeck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN2OTbo73t82695VfXtuXF6eIlAt-3whE',
    appId: '1:788354651482:ios:78c14ae11eb4d373550f63',
    messagingSenderId: '788354651482',
    projectId: 'owndeck-c-p',
    storageBucket: 'owndeck-c-p.firebasestorage.app',
    iosBundleId: 'com.example.owndeck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9hbfz5canvt87ce3mpMigT0HSDxBluVs',
    appId: '1:788354651482:web:0471f95c0b92cb2b550f63',
    messagingSenderId: '788354651482',
    projectId: 'owndeck-c-p',
    authDomain: 'owndeck-c-p.firebaseapp.com',
    storageBucket: 'owndeck-c-p.firebasestorage.app',
    measurementId: 'G-V4CP4V04YX',
  );
}
